### PR TITLE
Add optional auth in mongodb driver

### PR DESCRIPTION
**Pull request by fleg**
Just added missing auth  in mongodb driver

### CODE REVIEW

**Comment by fleg** [comment]
i have no idea why build is failed

**Comment by wzrdtales** [comment]
No problem, I'm currently investigating finding this failure. It's some kind of race condition which causes a failure sporadically in the build. This is due to something related to mongodb.

I just restarted the failed one.

**Comment by wzrdtales** [comment]
Merged.

Thank you for your contribution!

**Comment by wzrdtales** [comment]
Sorry, were out of time the last days.

Published within v0.9.11

**Pull request merged**
