### PR TITLE
Fix #468: avoid connecting to database before creation.

### LINKED ISSUE #468: `db-migrate db:create` not working as intended
I've been playing around for most of the morning with db-migrate and getting myself familiar with the ins and outs. One thing I have noticed is that the db:create command doesn't seem to work as I would have expected it. 

For example in my `database.json` I have configuration for a test database and a dev database. Now, when I run the `db-migrate db:create myapptest` I would expect to see that it creates a database to run my tests against. instead I get the following error: 

`[ERROR] Error: ER_BAD_DB_ERROR: Unknown database 'myapptest'` 

the whole reason for running the `db:create` command is _because_ that database doesn't exist and I want to create it.

Yet if I create the database and then run the command passing a a random name it will happily create any database I want. It will also claim that I have created the same database multiple times even when it has in fact created it once. 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/43274257-db-migrate-db-create-not-working-as-intended?utm_campaign=plugin&utm_content=tracker%2F73887&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F73887&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by RenWenshan**
fix #468

### CODE REVIEW

**Comment by RenWenshan** [comment]
Could you please have a review @wzrdtales?

**Comment by RenWenshan** [comment]
@wzrdtales ping

**Comment by archagy** [comment]
I had the same problem, I tested the change that he did and works well.

**Comment by RenWenshan** [comment]
@wzrdtales ping

**Comment by jesseteal** [comment]
@RenWenshan Thank you, this worked for me.

**Comment by RenWenshan** [comment]
Comment to keep this PR open

**Comment by wzrdtales** [comment]
sry, i completely drowned in work.

this should work in most cases, not sure about some of the other more special cases. But since those are broken right now anyways, I will merge this.

**Comment by ZsoltPath** [comment]
Hi @wzrdtales!

Would yo mind releasing this? And probably add to v1.0.0 as well?
Do you know when could this happen?

**Pull request merged**
