### PR TITLE
fix: allow special chars in password or user string

### PR DESCRIPTION
**Pull request by BorntraegerMarc**
This commit fixes a bug where special chars like `$`, `*` or `^` would cause the library to crash

### CODE REVIEW

**Comment by wzrdtales** [comment]
Thank you, highly appreciated @BorntraegerMarc !

I'm sick with fever, so have not quite any concentration at hand currently.I will try as early as possible, the only doubt  I have right now would be if this would actually break the other drivers. On which drivers and dbs did you tested this?

**Comment by BorntraegerMarc** [comment]
Oh oh, doesn't sound good @wzrdtales I wish you a speedy recovery 😷 

I only tested this with the MongoDB driver. So I can't speak for the other drivers. But I would assume this is a NodeJS general topic so I guess it shouldn't affect "normal" NodeJS drivers. But I'm no expert in this.

Shouldn't the tests cover some cases for the drivers?

**Comment by BorntraegerMarc** [comment]
fixed commitlint

**Comment by wzrdtales** [comment]
Ok I manage to test it with some other dbs and I couldn't reproduce your described problem at all. This seems to be solely a problem with the mongodb driver. What was the error you've got from the crash though?

**Comment by BorntraegerMarc** [comment]
The error was:
```
[ERROR] URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Url.parse (url.js:289:19)
    at Object.urlParse [as parse] (url.js:97:13)
    at module.exports (/usr/build/node_modules/db-migrate-mongodb/node_modules/mongodb/lib/url_parser.js:13:23)
    at connect (/usr/build/node_modules/db-migrate-mongodb/node_modules/mongodb/lib/mongo_client.js:485:3)
    at MongoClient.connect (/usr/build/node_modules/db-migrate-mongodb/node_modules/mongodb/lib/mongo_client.js:250:3)
    at Object.<anonymous> (/usr/build/node_modules/db-migrate-mongodb/index.js:294:23)
    at Promise._execute (/usr/build/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/usr/build/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/build/node_modules/bluebird/js/release/promise.js:79:10)
    at Object._run (/usr/build/node_modules/db-migrate-mongodb/index.js:288:12)
    at Object._createMigrationsCollection (/usr/build/node_modules/db-migrate-mongodb/index.js:24:17)
    at Object.createMigrationsTable (/usr/build/node_modules/db-migrate-mongodb/index.js:43:10)
    at /usr/build/node_modules/db-migrate/lib/commands/up.js:28:25
    at /usr/build/node_modules/db-migrate/connect.js:100:7
    at /usr/build/node_modules/db-migrate/lib/driver/index.js:104:7
```

**Comment by wzrdtales** [comment]
Hm yeah, that is really just a unique problem to mongodb here. So this does not apply to the core, can you add this change to the driver level for the mongo driver instead?

**Comment by BorntraegerMarc** [comment]
Sure :) Created https://github.com/db-migrate/mongodb/pull/35 and closing this PR...

**Pull request closed without merging**
