### PR TITLE
add mark command

### PR DESCRIPTION
**Pull request by AlexeyKhristov**
Can be used if need skip one or more migrations

### CODE REVIEW

**Comment by dready** [comment]
we wrote a similar tool in another language and been running this for years.. trust me.. there is always a time when you just want to mark the migration as done...

**Comment by sankethkatta** [comment]
Any thoughts on whether this feature would be suitable for node-db-migrate? This PR seems to have been abandoned a while back. If so, I would be happy to work on/fix up this PR.

My use case is for development. I use `sequelize` as my ORM which defines Models, which represent the current state of the database for my application to work with. I use `node-db-migrate` to manage migrations. When I make a migration in production, I update the according sequelize models to match the new schema, so that the ORM can interact with the database.

The problem I run into is in development. Tables are initialized by the ORM on a fresh local database, but this does not create / backfill the migrations table. Now, when I try to create a new migration, I have to manually backfill my table marking those migrations as "done" so that I can work on my next migration.

It seems to me that having this feature could be quite useful and allow node-db-migrate to play a bit nicer with ORMs. Other tools such as django's migration tool has a similar option [`--fake`][1]. 

[1]: https://docs.djangoproject.com/en/1.10/ref/django-admin/#cmdoption-migrate-fake

**Comment by sankethkatta** [comment]
@wzrdtales any thoughts on ^

**Comment by wzrdtales** [comment]
@sankethkatta Sorry for the late response on this...

Actually I think you should disable the ORMs feature to "migrate" your table, instead of skipping a migration, as I don't think this would be the solution to the problem, but just a workaround.

**Comment by sankethkatta** [comment]
@wzrdtales Could you explain a bit more on what you think a better workflow would be? I am trying to figure that out as well. I would still like to use the ORM for making queries and transforming fields in the database.

So when I create a new database locally, what is the best way to get it up to the state of production? As I mentioned, I have been using sequelize's "migrate" tool to simply create the tables locally from my models. Which then has the effect of getting out of sync with my node-db-migrate as its real migrations were never applied locally. This mainly causes problems when attempting to now test new migrations on the db.

Would it be better to auto-fill the "migrations" table when initializing the new db?
Or would a better option be to setup some system to export my production db schema and apply it locally?

**Comment by wzrdtales** [comment]
Closing this item for now, you may still discuss this, but please open a new proposal.

**Comment by wzrdtales** [comment]
And to answer the last question:

Actually migrations should be your source of truth, so either you first work with whatever tool you like to do stuff with your db and then translate it to a migration or you use migrations directly to alter the database. Which I would suggest, especially when working with others together and not just alone. There are plans to make working on migrations more "flux" friendly though.

**Comment by Gregoor** [comment]
A use case I had in mind:
As I'm calling migrate programmatically anyway, I'm generating a `schema.sql` after the migrations are completed (kinda like Rails' `schema.rb`). Now if db-migrate had a mark/skip feature new installations could use that schema file to quickly get to the most recent version, without having to run all the migrations.

**Comment by wzrdtales** [comment]
@Gregoor Wouldn't that be easier solved by dumping the migrations table too?

**Comment by Gregoor** [comment]
I can't think of a reason why I didn't think of that. Thanks 👍

**Pull request closed without merging**
