### PR TITLE
feat(migration): add typescript files support

### PR DESCRIPTION
**Pull request by RemyJeancolas**
This PR adds support for Typescript files, feel free to comment.

### CODE REVIEW

**Comment by wzrdtales** [comment]
Target for plugins #397

**Comment by wzrdtales** [comment]
Thank you for your contribution.

Won't be merged as this is a target for a plugin, rather than an addition directly to db-migrate. Plugin support is just freshly introduced and I have also just added the hook to register precompiler.

Take a look here, this is the coffee script module I moved out into its own plugin now:

https://github.com/db-migrate/plugin-coffee

**Comment by RemyJeancolas** [comment]
I understand, no problem for me.

I will look at the [`plugin-coffee`](https://github.com/db-migrate/plugin-coffee) repo and update my code to provide a `plugin-typecript` based on it.
In order to follow the "new way", could you create a `plugin-typescript` repo, so I could make a PR in this repo for the Typescript integration ?

Thanks by advance.

**Comment by wzrdtales** [comment]
Sure: https://github.com/db-migrate/plugin-typescript

Always feel free to just push out your own extensions, but as long as those are small I have no problem to take over their maintenance, which I guess is what you want :)

**Comment by wzrdtales** [comment]
To help developers there is now also a module called `db-migrate-pkgkit` which needs to be installed globally and delivers a cli to the developer accessable via the command db-migrate-pkgkit. This cli is aimed to make driver and plugin creation easier. Yet only build for plugins though. This plugin you're going to write for this addition is quite small, so you might not need it, but just wanted to let current plugin devs know.

**Comment by RemyJeancolas** [comment]
Thanks for the info, I just created a PR for the plugin-typescript repo, it's available [here](https://github.com/db-migrate/plugin-typescript/pull/1).

**Pull request closed without merging**
