### PR TITLE
fix(create): Fix create when using db-migrate as module

### PR DESCRIPTION
**Pull request by gmanriqueUy**
Bug introduced on #485

Fixes: #493

### CODE REVIEW

**Comment by wzrdtales** [comment]
Awesome!
I really appreciate your contribution :)

And sry for the delay, I have little to no time currently due to some approaching events.

**Comment by wzrdtales** [comment]
Test fails as you call a new instance without providing a config object or other alternatives, so it searches for database.json.

Here is an example where an empty config is passed over:

https://github.com/db-migrate/node-db-migrate/blob/master/test/integration/api_test.js#L216

**Comment by gmanriqueUy** [comment]
@wzrdtales I made some changes and the tests are passing. Tell me if you prefer another way of doing it.

**Comment by wzrdtales** [comment]
This is totally fine :)

**Comment by wzrdtales** [comment]
Was published as bug fix under

+ db-migrate@0.10.0-beta.24

**Pull request merged**
