### PR TITLE
Update vulnerable pack 'deep-extend' and OOD deps

### PR DESCRIPTION
**Pull request by drGrove**
* Update deep-extend to latest version as vulnerability has been patched
* Update balance-match to latest version to not be out of date
* Update dotenv to latest version to not be out of date

### CODE REVIEW

**Comment by wzrdtales** [comment]
@drGrove Have you validated that your OOD updates did not trigger any breaking changes? Especially as these are major version jumps. This shouldn't be just upgraded without having a second look at it.

**Comment by drGrove** [comment]
Balance match has no listed breaking changes.
Dotenv changed it's default path check to the location of where the process is started from. Most runner scripts tend to handle moving the the root of a project prior to running so I don't think this should be an issue.

**Comment by drGrove** [comment]
This should be ready for another review. Because I force-pushed on my side, gh didn't update.

**Comment by drGrove** [comment]
Ping

**Comment by wzrdtales** [comment]
Thanks for pinging :) I put that on my schedule for the weekend

**Comment by drGrove** [comment]
Ping

**Comment by drGrove** [comment]
Ping

**Comment by MichaelRBond** [comment]
Is there any movement on this Pull Request? 

We also need to get deep-extend updated. Thanks.

**Comment by wzrdtales** [comment]
Yes sry, just starting to organize my open source work again, but haven't had much time at hand since a lot of things are happening in the background (founding my own company and a lot of different stuff). I plan to invest more time into db-migrate in the near future and currently also search some sponsors, to create actually room for this.

**Pull request merged**
