### PR TITLE
Add enum support and update Decimal to take arguments

### PR DESCRIPTION
**Pull request by dickfickling**

### CODE REVIEW

**Comment by sahilsk** [comment]
are there any plan of supporting enum  datatype ? @wzrdtales

**Comment by wzrdtales** [comment]
@sahilsk Actually you can add enums by doing the following:

```javascript
        country_id:
        {
            type: 'enum(\'DE\',\'EN\',\'FR\',\'US\',\'GB\')',
            notNull: true,
            length: 0
        },
```

Actually it is not planned to give explicit support in general to it. Thus it wont be part of the default API, but it could be a non default extension to the soon stand alone mysql driver.

**Comment by shanben7** [comment]
@wzrdtales This syntax you gave for adding enum doesn't work for me. For this code (in createTable)
`    status:
      {
        type: 'enum(\'scheduled\',\'pending\')',
        notNull: true,
        length: 0
      },`

I get this when I try to run the migration:
`[WARN] Using unknown data type ENUM('SCHEDULED','PENDING','SENT','FAILED')`
`[ERROR] error: type "enum" does not exist`

I know that I can use raw sql to add the enumeration, but it would be nicer to use the API.

**Comment by Cezarion** [comment]
Hello, 
You can use the api :
```js
exports.up = function(db, callback) {
  async.series([
    db.addColumn.bind(
      db,
      "size",
      "type",{
        type: 'enum',
        notNull: true,
        length: '\'xs\',\'s\',\'m\',\'l\',\'xl\'',
        defaultValue: 'solo'
    })
  ],callback)
};
```

**Comment by pak11273** [comment]
I'm getting the same errors as @shanben7 .  Any progress in this area?

**Pull request closed without merging**
