### PR TITLE
Fixes programatic cmd options

### PR DESCRIPTION
**Pull request by BorntraegerMarc**
Fix for https://github.com/db-migrate/node-db-migrate/issues/557

### CODE REVIEW

**Comment by wzrdtales** [comment]
Since it was my fault, that I did not require to add a test last time, which was also reasoning for this to happen, I added it on my own now :)

**Comment by wzrdtales** [comment]
Can you please rebase against the current master and incorporate the new test? It should not fail if it works though :)

**Comment by BorntraegerMarc** [comment]
@wzrdtales I merged master into this branch but somehow the CI is not starting...

**Comment by wzrdtales** [comment]
@BorntraegerMarc Always rebase instead of merging when getting something from an upstream repo.

**Comment by wzrdtales** [comment]
But currently many things are strange here on github. Also the bots do not work as intended.

**Comment by wzrdtales** [comment]
You normally always want to build upon the master branch instead of merging in the master branch, which is the difference between rebasing and merging. Merging moves the master on top of your changes in a merge commit, rebasing applies your changes to the current master instead.

**Comment by wzrdtales** [comment]
I just rebased and merged manually here:

https://github.com/db-migrate/node-db-migrate/commit/0223c23ec54a33a7cde09bca4f65eec7f282d9b4

Closing.

**Comment by wzrdtales** [comment]
Published as 
+ db-migrate@0.10.7

**Pull request closed without merging**
