### PR TITLE
Add docker-compose.yml to start databases in Docker containers

### PR DESCRIPTION
**Pull request by Maxwell2022**
I've added a `docker-compose.yml` configuration file to start the following databases: `mysql`, `postgres` and `mongo`.

Test are still failing because some of the connection are hardcoded. I tried to have a look but I could not understand the logic so I didn't touch anything.

### CODE REVIEW

**Comment by wzrdtales** [comment]
I will have a look later thank you for your contribution

**Comment by wzrdtales** [comment]
This will need to have an example docker config to be be included though.

The question is, to have a consistent way to address the containers, we will need to add a node js execution image with the dbs linked.

**Comment by wzrdtales** [comment]
Actually forgot the questions: The question is, to have a consistent way to address the containers, we will need to add a node js execution image with the dbs linked, so how do we make the usage more convinient again.
Working from inside the docker container is most of the time not a good option for the developer.

**Comment by Maxwell2022** [comment]
I was thinking that the `db.config.example.json` in the `test` folder could be updated with the configuration that is in the `docker-compose.yml` however, we need to fix every hardcoded configuration in the tests first. Here is few examples:

- https://github.com/db-migrate/node-db-migrate/blob/master/test/driver/pg_schema_test.js#L9
- https://github.com/db-migrate/node-db-migrate/blob/master/test/driver/pg_schema_test.js#L23

I still don't really understand what these tests are here for? What are they meant to tests exactly?

**Comment by wzrdtales** [comment]
@Maxwell2022 This is true for your your examples, but the config from test folder is not being updated. I want a consistent setup for docker container if we introduce them. Thus also a config dedicated to this containers that do not change, this might be either the default config of the project itself or part of the entrypoint of the docker container hosting the node app where the data container are linked to.

**Comment by wzrdtales** [comment]
@Maxwell2022 Well that is history: https://github.com/db-migrate/node-db-migrate/commits/master/test/driver/pg_schema_test.js

Actually it was introduced to test the functionality of changing the schema passed as parameter to the driver.

**Pull request closed without merging**
